### ISSUE TITLE
UUID as ID

### ISSUE THREAD

**Issue by darenegade** [xdoo/spring_data_jpa_cache_demo#1]
Das Problem mit der UUID ist, dass diese überschrieben wird beim Speichern. D.h. `findeOne` funktioniert schon, nur nicht mit deiner festen UUID, da die Entität unter einer anderen UUID gespeichert ist.

```java
        Animal createdBagira = this.animalRepo.findAll().iterator().next();
        Animal bagira = this.animalRepo.findOne(createdBagira.getOid());

        assertNotNull(bagira);
        assertNotEquals(bagira.getOid(), UUID.fromString(OID_BAGIRA));
```

**Comment by xdoo** [comment]
Manchmal sitzt der Fehler vor dem Rechner :) Danke.
